### ISSUE TITLE
Empty mandatory fields are not highlighted in Add Resources page on clicking Cancel button in go back confirmation box

### ISSUE THREAD

**Issue by nerdy-rups** [Audienix/InterPrep#52]
**Follow the steps given below to get to the issue:** 

1. Go to Resources tab
2. Click on + button to start adding new resource
3. Without entering data in all or even 1 of the mandatory fields, try to get back to previous page
4. Unsaved Resource dialog box pops up with Cancel and Ok buttons. Click on the Cancel button
5. Mandatory fields on the page are not highlighted like they are done in Add Interview page upon following the exact same steps in 1-4

**Comment by Arighna88** [comment]
@nerdy-rups If you could upload Screenshot/Video it would be helpful.
