### ISSUE TITLE
Notes getting deleted on touching them from Notes list page

### ISSUE THREAD

**Issue by nerdy-rups** [Audienix/InterPrep#55]
**Follow the steps to given below to get to the issue:** 

1. From notes list page, select any interview and click on 'Add Notes' 
2. Add note information - Interview segment, topic, question(s)
3. Come back to previous page. Added notes will be listed in the interview card
4. Touch the notes list - those get deleted. 

_Expected - No action on touching the notes list (TBD)_

**Comment by Audienix** [comment]
This will be fixed in next release.

**Comment by nerdy-rups** [comment]
Fixed. Notes not getting deleted on touch.
