### ISSUE TITLE
Unexpected space before '?' mark in go-back confirmation box in add resources screen

### ISSUE THREAD

**Issue by nerdy-rups** [Audienix/InterPrep#57]
Text inside the go-back confirmation box in Resource Screen should be: 
"Your learning resource would not be saved as you have not filled up mandatory details. Go **back?**" .

**Comment by Audienix** [comment]
This will be fixed in next release.

**Comment by nerdy-rups** [comment]
Fixed. 
![Screenshot_20230823-190824](https://github.com/Audienix/InterPrep/assets/64094395/3588e946-051f-43c6-8337-019643b35120)

**Comment by nerdy-rups** [comment]
Fixed. 
#
![Screenshot_20230823-190824](https://github.com/Audienix/InterPrep/assets/64094395/3bbb9dde-52b0-482d-a783-2c083a74409c)
