### ISSUE TITLE
Time format getting changed when trying to change existing time value

### ISSUE THREAD

**Issue by Audienix** [Audienix/InterPrep#64]
PreCondition - Device settings has 24 hour time format.
1. In `Add Interview` Screen  - 1st time select a time value from TimePicker in  Time Input box and it will show time in 24 hours format.
2. Open the TimePicker again to change time. 

Issue 1 - TimePicker does not show the existing user selected time in 24 hours format.
Issue 2 - After selection of time 2nd time, time does not get displayed in Input box in 24 hours format. It shows in 12 hour format.

Same Issue can be found when opening a Time Picker from `Edit Interview` Screen.

**Comment by nerdy-rups** [comment]
Not seen in the latest release build. Marking as closed.
