### ISSUE TITLE
Show "Add Question" button option in "Edit Notes" Screen

### ISSUE THREAD

**Issue by Audienix** [Audienix/InterPrep#66]
In this screen show "Add Question" option to let user add question in "Edit Notes" screen.

![image](https://github.com/Audienix/InterPrep/assets/33220667/54560cdd-cfa7-4464-ac07-0284ba405ad9)

**Comment by nerdy-rups** [comment]
Fixed. Button added. It's working. 
![Uploading Screenshot_20230823-190232.png…]()

**Comment by nerdy-rups** [comment]
Fixed. Button added and is working. 
![Screenshot_20230823-190232](https://github.com/Audienix/InterPrep/assets/64094395/b6c80af3-cf6c-4fa8-bc57-217b74532cfa)
